
language: python

python:
  - '2.6'
  - '2.7'

install:
  - pip install --use-mirrors flake8 pytest
  - make develop_deps

script:
  - make test
  - flake8 . --exclude='libs,third_party' --max-complexity 6
