application: rae-quel
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url:          /.*
  script:       raequel.app

libraries:
- name:     lxml
  version:  latest

- name: jinja2
  version: latest
